### ISSUE TITLE
chromium: inspect bug

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#175] opened 2021-03-09 00:36 UTC
I've updated to version ...-180 from ...150

Everytime I try to inspect element on the page nothing happens, but in the console there is this error: 

[4423:4423:0308/193307.086765:ERROR:CONSOLE(7)] "Uncaught (in promise) ReferenceError: Intl is not defined", source: devtools://devtools/bundled/i18n/i18n.js (7)

It looks like some js broke

**Comment by git-bruh** [comment] 2021-03-09 11:37
This is caused by me experimenting with flags, `v8_enable_i18n_support=false` (tried to drop icu, but it's required by devtools so have removed the flag now). Will be fixed when i send a PR to update to ver 89 (Just waiting for ungoogled-chromium to release a new patchset tarball).

**Closed** 2021-03-10 14:19 UTC
