### ISSUE TITLE
Package chromium

### ISSUE THREAD

**Issue by jedahan** [kiss-community/repo-community#27] opened 2021-01-06 15:45 UTC
This is a tracking ticket for native chromium on musl.

Currently, flatpak is our best bet.

Once we have chromium, we can tackle ungoogled-chromium and electron.

**Comment by git-bruh** [comment] 2021-01-13 12:32
my (currently failing) attempt: https://github.com/git-bruh/community/tree/chromium/community/chromium

**Comment by git-bruh** [comment] 2021-01-13 12:43
fails with this output on both gcc and clang, currently building on glibc

```
[11108/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_editpath.o
[11109/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_editpage.o
[11110/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_editimg.o
[11111/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_doc.o
[11112/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_dataavail.o
[11113/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_catalog.o
[11114/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_attachment.o
[11115/42952] CXX obj/third_party/pdfium/fpdfsdk/fpdfsdk/fpdf_annot.o
ninja: job failed: python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./mksnapshot" -- g++ -pie -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -rdynamic -pie -Wl,--disable-new-dtags -o "./mksnapshot" -Wl,--start-group @"./mksnapshot.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lz
/usr/bin/ld: obj/v8/v8_base_without_compiler/snapshot-utils.o: in function `v8::internal::Checksum(v8::internal::Vector<unsigned char const>)':
snapshot-utils.cc:(.text+0x14): undefined reference to `Cr_z_adler32'
/usr/bin/ld: snapshot-utils.cc:(.text+0x20): undefined reference to `Cr_z_adler32'
/usr/bin/ld: obj/v8/v8_base_without_compiler/snapshot-utils.o: in function `v8::internal::Checksum(v8::internal::Vector<unsigned char const>, v8::internal::Vector<unsigned char const>)':
snapshot-utils.cc:(.text+0x4e): undefined reference to `Cr_z_adler32'
/usr/bin/ld: snapshot-utils.cc:(.text+0x5b): undefined reference to `Cr_z_adler32'
/usr/bin/ld: snapshot-utils.cc:(.text+0x68): undefined reference to `Cr_z_adler32'
collect2: error: ld returned 1 exit status
ninja: subcommand failed
```

**Comment by noocsharp** [comment] 2021-01-13 23:37
I've also been working on chromium, but I didn't get anything like that 🤔

**Comment by git-bruh** [comment] 2021-01-14 07:56
@noocsharp Could you share your build file ?

**Comment by git-bruh** [comment] 2021-01-14 08:13
Finally got it to build, but it depends on dbus, atk-bridge and at-spi2-core. Will have to see if i can stub out the dbus dependency with https://github.com/dylanaraps/libdbus-stub or https://github.com/clbr/nobus, then try a musl build

**Comment by git-bruh** [comment] 2021-01-14 09:54
OK now the handshake issue is suddenly gone (?), will figure out gtk later, now will start build on musl

Sorry for spamming the issue

**Comment by git-bruh** [comment] 2021-01-14 11:36
musl patches needing updates:
```
musl-fixes.patch
musl-no-mallinfo.patch
musl-sandbox.patch
```

**Comment by noocsharp** [comment] 2021-01-14 16:06
I have a successful build on musl on top of 87 by stealing from alpine and arch.

**Comment by jedahan** [comment] 2021-01-14 16:56
@noocsharp didn't push yet? browsing the web interface doesn't show chromium...

**Comment by noocsharp** [comment] 2021-01-14 17:01
The web interface is broken atm, haven't gotten around to fixing it.

**Comment by noocsharp** [comment] 2021-01-14 17:35
I should mention that at the very least installing doesn't work yet, so the build script should just be used as a guide for building locally for now.

**Comment by git-bruh** [comment] 2021-01-14 18:23
@noocsharp was getting gssapi related include errors, so just copied those from artix earlier as a temporary hack

While going through this gentoo overlay https://github.com/smaeul/portage-overlay
to remove dbus, saw that "use_kerberos=false" is a valid build option too.

**Comment by git-bruh** [comment] 2021-01-15 14:51
Got a build on musl finally, earlier kept failing due to something related to `OutputToStreamWithPrefix` with the execinfo patch, found another patch for the same and seems to work, need to update in repo

Sandbox doesn't work under musl, probably something with me running in a chroot (glibc sandbox works fine with no SUID), will have to test on a real KISS install 

Here's a musl binary, would be great if someone else tested it too

https://anonfiles.com/nam2Bf97p6/test_1-1.tar_xz
sha256 `80c8b4e989f2137ef3126237bba5e7e13bb379c5a2635d7c0337f9e86a2f7456`

**Comment by noocsharp** [comment] 2021-01-15 16:20
I'm on a real kiss install and I get the following output to stderr on startup:
```
[19147:19147:0115/101319.441968:ERROR:browser_dm_token_storage_linux.cc(94)] Error: /etc/machine-id contains 0 characters (32 were expected).
[19170:19170:0115/101319.546745:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

I think this means sandbox doesn't work, but I'm not sure. The first error can easily be fixed by adding a file, and maybe by patching it out.

**Comment by git-bruh** [comment] 2021-01-15 16:35
The first one is harmless (dbus related), second one im not so sure about but if the sandbox wasn't working, chromium would ask you to launch with `--no-sandbox`, will check this myself too.

Thanks for testing it 👍

**Comment by git-bruh** [comment] 2021-01-15 16:37
The browser actually works, right ? or just exits after those 2?

**Comment by noocsharp** [comment] 2021-01-15 16:43
Works great, at least with my limited testing.

**Comment by git-bruh** [comment] 2021-01-15 16:49
Nice

The second error seems to be mostly(?) harmless aswell, looks mesa related, i guess i didn't get it cuz nvidia drivers

https://discussion.fedoraproject.org/t/state-of-chrome-ium-87-with-wayland/23713/3
https://github.com/nwjs/nw.js/issues/7316#issuecomment-573481441
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433;msg=10
https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/2
https://github.com/Eloston/ungoogled-chromium/issues/519#issuecomment-425501579

**Comment by noocsharp** [comment] 2021-01-16 03:28
@git-bruh 
When I try to build your chromium package, I get the following:
```
ninja: job failed: python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./character_data_generator" -- g++ -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -rdynamic -pie -Wl,--disable-new-dtags -o "./character_data_generator" -Wl,--start-group @"./character_data_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0
/usr/bin/ld: obj/base/base/stack_trace.o: in function `base::debug::StackTrace::OutputToStream(std::ostream*) const':
stack_trace.cc:(.text+0xc3): undefined reference to `base::debug::StackTrace::OutputToStreamWithPrefix(std::ostream*, char const*) const'
collect2: error: ld returned 1 exit status
ninja: job failed: python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./schema_org_name_generator" -- g++ -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -rdynamic -pie -Wl,--disable-new-dtags -o "./schema_org_name_generator" -Wl,--start-group @"./schema_org_name_generator.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0
/usr/bin/ld: obj/base/base/stack_trace.o: in function `base::debug::StackTrace::OutputToStream(std::ostream*) const':
stack_trace.cc:(.text+0xc3): undefined reference to `base::debug::StackTrace::OutputToStreamWithPrefix(std::ostream*, char const*) const'
collect2: error: ld returned 1 exit status
ninja: job failed: python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./crashpad_handler" -- g++ -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -rdynamic -pie -Wl,--disable-new-dtags -o "./crashpad_handler" -Wl,--start-group @"./crashpad_handler.rsp"  -Wl,--end-group  -latomic -ldl -lpthread -lrt -lgmodule-2.0 -lglib-2.0 -lgobject-2.0 -lgthread-2.0
/usr/bin/ld: obj/base/base/stack_trace.o: in function `base::debug::StackTrace::OutputToStream(std::ostream*) const':
stack_trace.cc:(.text+0xc3): undefined reference to `base::debug::StackTrace::OutputToStreamWithPrefix(std::ostream*, char const*) const'
```
I believe it can be solved by ifdefing the inside of the OutputToStream method in `base/debug/stack_trace.cc` to only be enabled with glibc.

**Comment by git-bruh** [comment] 2021-01-16 11:52
Having a hard time figuring out the gtk theme crash, did `ldd` on arch's `libgtk-3.so`, it linked to libcloudproviders and atk-bridge aswell. So i packaged both, even linked gtk3 to both of them, but the crash persists

Also for some reason `libcloudproviders.so.0` doesn't show up when i do `ldd /usr/lib/chromium/chromium`, if i remove libcloudproviders package, its just gone from `ldd` and doesn't even show up as "not found" ????

**Comment by git-bruh** [comment] 2021-01-16 12:00
Arch's chromium links to these libs
```
	libicui18n.so.68 => not found
	libicuuc.so.68 => not found
	libatk-bridge-2.0.so.0 => not found
	libcups.so.2 => not found
	libdbus-1.so.3 => not found
	libre2.so.9 => not found
	libsnappy.so.1 => not found
	libminizip.so.1 => not found
	libatspi.so.0 => not found
```

In our case, atspi, dbus and cups are disabled, and rest are not used from system libs, so not sure where the problem is coming from :/

**Comment by git-bruh** [comment] 2021-01-16 14:40
Package is almost done now, ungoogled built on glibc successfully, waiting for musl build to finish.

And the gtk theme segfault isn't related to the build itself, the same issue was present even when i tried a binary few weeks back

**Comment by noocsharp** [comment] 2021-01-16 16:49
Does it output anything to stderr when it crashes?

**Comment by git-bruh** [comment] 2021-01-16 17:02
@noocsharp  nah its a segfault http://ix.io/2Me4 (gdb)
idk why it doesn't happen if i set my `LD_LIBRARY_PATH` to arch's cuz i tried to build gtk with similar options aswell

**Comment by git-bruh** [comment] 2021-01-17 05:21
doing a `diff` between the ldd output and the output with `LD_LIBRARY_PATH` shows some extra libs but none of them seem to be related to the segfault http://ix.io/2MhH The "problem" lies in how KISS builds one of it's libs i guess

**Comment by git-bruh** [comment] 2021-01-17 05:36
So using all libs from arch, and just `LD_PRELOAD`-ing KISS's gtk3 lib causes the same segfault, `LD_PRELOAD`-ing other libs doesn't cause other crashes or anything. Will try building a :b: loated gtk3 on KISS and see if it happens

**Comment by git-bruh** [comment] 2021-01-17 06:14
Figured it out finally! All i had to do was remove `--enable-debug=no` from KISS's gtk3 build :tada:

**Closed** 2021-01-17 11:33 UTC
